// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.0
// source: protos/edgewatcher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatcherServiceClient interface {
	ReportEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type watcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherServiceClient(cc grpc.ClientConnInterface) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) ReportEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/watcher.WatcherService/ReportEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatcherServiceServer is the server API for WatcherService service.
// All implementations must embed UnimplementedWatcherServiceServer
// for forward compatibility
type WatcherServiceServer interface {
	ReportEvent(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedWatcherServiceServer()
}

// UnimplementedWatcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatcherServiceServer struct {
}

func (UnimplementedWatcherServiceServer) ReportEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedWatcherServiceServer) mustEmbedUnimplementedWatcherServiceServer() {}

// UnsafeWatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServiceServer will
// result in compilation errors.
type UnsafeWatcherServiceServer interface {
	mustEmbedUnimplementedWatcherServiceServer()
}

func RegisterWatcherServiceServer(s grpc.ServiceRegistrar, srv WatcherServiceServer) {
	s.RegisterService(&WatcherService_ServiceDesc, srv)
}

func _WatcherService_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watcher.WatcherService/ReportEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).ReportEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatcherService_ServiceDesc is the grpc.ServiceDesc for WatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watcher.WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportEvent",
			Handler:    _WatcherService_ReportEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/edgewatcher.proto",
}
